const USERS = process.env.REACT_APP_USERS
const PWBI = process.env.REACT_APP_PWBI
const ROLES = process.env.REACT_APP_ROLES
const CREAR_USER = process.env.REACT_APP_CREAR_USER
const BORRAR_USER = process.env.REACT_APP_BORRAR_USER
const MOD_USER = process.env.REACT_APP_MOD_USER
const PRODUCTOS = process.env.REACT_APP_PRODUCTOS
const TIPO_PRODUCTO = process.env.REACT_APP_TIPO_PRODUCTO
const CREAR_PRODUCTO = process.env.REACT_APP_CREAR_PRODUCTO
const BORRAR_PRODUCTO = process.env.REACT_APP_BORRAR_PRODUCTO
const MOD_PRODUCTO = process.env.REACT_APP_MOD_PRODUCTO
const CREAR_VENTA = process.env.REACT_APP_CREAR_VENTA
const CREAR_DETALLE_VENTA = process.env.REACT_APP_CREAR_DETALLE_VENTA
const MOD_CAN_INV = process.env.REACT_APP_MOD_INV

export default {
    USERS,
    PWBI,
    ROLES,
    CREAR_USER,
    BORRAR_USER,
    MOD_USER,
    PRODUCTOS,
    TIPO_PRODUCTO,
    CREAR_PRODUCTO,
    BORRAR_PRODUCTO,
    MOD_PRODUCTO,
    CREAR_VENTA,
    CREAR_DETALLE_VENTA,
    MOD_CAN_INV,
};


